/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    RoleRegistry: {
      address:
        "0x7cec2a5dbc14cf24fcc590fb61a8d5466b03b9f298629ee40efe1e283130e05",
      abi: [
        {
          type: "impl",
          name: "RoleRegistryImpl",
          interface_name:
            "contracts::role_registry::RoleRegistry::IRoleRegistry",
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::role_registry::RoleRegistry::IRoleRegistry",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_role",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u8",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_role",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "role",
                  type: "core::integer::u8",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_partner",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "partner_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_partner_id",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_operator",
              inputs: [
                {
                  name: "operator",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "partner_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_operator_partner_id",
              inputs: [
                {
                  name: "operator",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_operator_enabled",
              inputs: [
                {
                  name: "operator",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "enable_operator",
              inputs: [
                {
                  name: "operator",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "disable_operator",
              inputs: [
                {
                  name: "operator",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "is_platform_admin",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_bloodbank",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_partner",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_operator",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::role_registry::RoleRegistry::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "old_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::role_registry::RoleRegistry::RoleUpdated",
          kind: "struct",
          members: [
            {
              name: "account",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "old_role",
              type: "core::integer::u8",
              kind: "data",
            },
            {
              name: "new_role",
              type: "core::integer::u8",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::role_registry::RoleRegistry::PartnerSet",
          kind: "struct",
          members: [
            {
              name: "account",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "partner_id",
              type: "core::integer::u32",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::role_registry::RoleRegistry::OperatorSet",
          kind: "struct",
          members: [
            {
              name: "operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "partner_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "enabled",
              type: "core::bool",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::role_registry::RoleRegistry::OperatorEnabledChanged",
          kind: "struct",
          members: [
            {
              name: "operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "enabled",
              type: "core::bool",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::role_registry::RoleRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "contracts::role_registry::RoleRegistry::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "RoleUpdated",
              type: "contracts::role_registry::RoleRegistry::RoleUpdated",
              kind: "nested",
            },
            {
              name: "PartnerSet",
              type: "contracts::role_registry::RoleRegistry::PartnerSet",
              kind: "nested",
            },
            {
              name: "OperatorSet",
              type: "contracts::role_registry::RoleRegistry::OperatorSet",
              kind: "nested",
            },
            {
              name: "OperatorEnabledChanged",
              type: "contracts::role_registry::RoleRegistry::OperatorEnabledChanged",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x400b3799c08fd250faa369aa6cdbc266028806cfca2f4d89cfc967d929e4578",
    },
    BloodworksCore: {
      address:
        "0x2df4aad59bf7e3e0100db6e2454e857b2e919215578eccf129e19384f79f00f",
      abi: [
        {
          type: "impl",
          name: "BloodworksCoreImpl",
          interface_name:
            "contracts::bloodworks_core::BloodworksCore::IBloodworksCore",
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::bloodworks_core::BloodworksCore::IBloodworksCore",
          items: [
            {
              type: "function",
              name: "issue_credential",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "record_donation",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_role_registry",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_status",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "(core::bool, core::integer::u32, core::integer::u64, core::integer::u64, core::bool)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_active",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "create_perk",
              inputs: [
                {
                  name: "partner_id",
                  type: "core::integer::u32",
                },
                {
                  name: "perk_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_perk_enabled",
              inputs: [
                {
                  name: "partner_id",
                  type: "core::integer::u32",
                },
                {
                  name: "perk_id",
                  type: "core::integer::u32",
                },
                {
                  name: "enabled",
                  type: "core::bool",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "perk_exists",
              inputs: [
                {
                  name: "partner_id",
                  type: "core::integer::u32",
                },
                {
                  name: "perk_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "perk_enabled",
              inputs: [
                {
                  name: "partner_id",
                  type: "core::integer::u32",
                },
                {
                  name: "perk_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_perk_total_redemptions",
              inputs: [
                {
                  name: "partner_id",
                  type: "core::integer::u32",
                },
                {
                  name: "perk_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_partner_total_redemptions",
              inputs: [
                {
                  name: "partner_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "redeem_perk",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "perk_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "role_registry",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "cooldown_seconds",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bloodworks_core::BloodworksCore::CredentialIssued",
          kind: "struct",
          members: [
            {
              name: "donor",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bloodworks_core::BloodworksCore::DonationRecorded",
          kind: "struct",
          members: [
            {
              name: "donor",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "donation_count",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "last_donation_ts",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "cooldown_end_ts",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bloodworks_core::BloodworksCore::PerkCreated",
          kind: "struct",
          members: [
            {
              name: "partner_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "perk_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "created_at",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bloodworks_core::BloodworksCore::PerkEnabledChanged",
          kind: "struct",
          members: [
            {
              name: "partner_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "perk_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "enabled",
              type: "core::bool",
              kind: "data",
            },
            {
              name: "changed_at",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bloodworks_core::BloodworksCore::PerkRedeemed",
          kind: "struct",
          members: [
            {
              name: "donor",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "partner_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "perk_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "redeemed_at",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bloodworks_core::BloodworksCore::Event",
          kind: "enum",
          variants: [
            {
              name: "CredentialIssued",
              type: "contracts::bloodworks_core::BloodworksCore::CredentialIssued",
              kind: "nested",
            },
            {
              name: "DonationRecorded",
              type: "contracts::bloodworks_core::BloodworksCore::DonationRecorded",
              kind: "nested",
            },
            {
              name: "PerkCreated",
              type: "contracts::bloodworks_core::BloodworksCore::PerkCreated",
              kind: "nested",
            },
            {
              name: "PerkEnabledChanged",
              type: "contracts::bloodworks_core::BloodworksCore::PerkEnabledChanged",
              kind: "nested",
            },
            {
              name: "PerkRedeemed",
              type: "contracts::bloodworks_core::BloodworksCore::PerkRedeemed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x769ebd1d0e580f2a3ea2ef49ff9cf1149779bc047153fb88605aecb7e8e040f",
    },
  },
} as const;

export default deployedContracts;
