/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    RoleRegistry: {
      address:
        "0x421e60e85984aadc0bfe475c69418a954fc3fc9a22473c6d82b4e6e689916f",
      abi: [
        {
          type: "impl",
          name: "RoleRegistryImpl",
          interface_name:
            "contracts::role_registry::RoleRegistry::IRoleRegistry",
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::role_registry::RoleRegistry::IRoleRegistry",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_role",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u8",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_role",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "role",
                  type: "core::integer::u8",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "is_platform_admin",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_bloodbank_admin",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_partner",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_partner_id",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_partner_id",
              inputs: [
                {
                  name: "account",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "partner_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::role_registry::RoleRegistry::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "old_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::role_registry::RoleRegistry::RoleUpdated",
          kind: "struct",
          members: [
            {
              name: "account",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "old_role",
              type: "core::integer::u8",
              kind: "data",
            },
            {
              name: "new_role",
              type: "core::integer::u8",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::role_registry::RoleRegistry::PartnerIdUpdated",
          kind: "struct",
          members: [
            {
              name: "account",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "partner_id",
              type: "core::integer::u32",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::role_registry::RoleRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "contracts::role_registry::RoleRegistry::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "RoleUpdated",
              type: "contracts::role_registry::RoleRegistry::RoleUpdated",
              kind: "nested",
            },
            {
              name: "PartnerIdUpdated",
              type: "contracts::role_registry::RoleRegistry::PartnerIdUpdated",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x3c396fd1873944f0bccf26679d24617b1ce5a5c78517cd17ddcecaf0913976c",
    },
    BloodworksCore: {
      address:
        "0x1eb6cdae23d964cb20b2f7f243d05ed34030a22919ab4be4a5b1ffa9b8b5481",
      abi: [
        {
          type: "impl",
          name: "BloodworksCoreImpl",
          interface_name:
            "contracts::bloodworks_core::BloodworksCore::IBloodworksCore",
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::bloodworks_core::BloodworksCore::IBloodworksCore",
          items: [
            {
              type: "function",
              name: "issue_credential",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "record_donation",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_role_registry",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_status",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "(core::bool, core::integer::u32, core::integer::u64, core::integer::u64, core::bool)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_active",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "redeem_perk",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "perk_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "is_redeemed",
              inputs: [
                {
                  name: "donor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "partner_id",
                  type: "core::integer::u32",
                },
                {
                  name: "perk_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "role_registry",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "cooldown_seconds",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bloodworks_core::BloodworksCore::CredentialIssued",
          kind: "struct",
          members: [
            {
              name: "donor",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bloodworks_core::BloodworksCore::DonationRecorded",
          kind: "struct",
          members: [
            {
              name: "donor",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "donation_count",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "last_donation_ts",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "cooldown_end_ts",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bloodworks_core::BloodworksCore::PerkRedeemed",
          kind: "struct",
          members: [
            {
              name: "donor",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "partner_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "perk_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "redeemed_at",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::bloodworks_core::BloodworksCore::Event",
          kind: "enum",
          variants: [
            {
              name: "CredentialIssued",
              type: "contracts::bloodworks_core::BloodworksCore::CredentialIssued",
              kind: "nested",
            },
            {
              name: "DonationRecorded",
              type: "contracts::bloodworks_core::BloodworksCore::DonationRecorded",
              kind: "nested",
            },
            {
              name: "PerkRedeemed",
              type: "contracts::bloodworks_core::BloodworksCore::PerkRedeemed",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x717306c772917205f1ca217ff69fb3b2e0215418bd9e59d5439739fc431ffa8",
    },
  },
} as const;

export default deployedContracts;
